INSERT INTO MPAS (NAME)
VALUES ('G');
INSERT INTO MPAS (NAME)
VALUES ('PG');
INSERT INTO MPAS (NAME)
VALUES ('PG-13');
INSERT INTO MPAS (NAME)
VALUES ('R');
INSERT INTO MPAS (NAME)
VALUES ('NC-17');
INSERT INTO GENRES (name) VALUES ('Комедия');
INSERT INTO GENRES (name) VALUES ('Драма');
INSERT INTO GENRES (name) VALUES ('Мультфильм');

INSERT INTO GENRES (name) VALUES ('Триллер');
INSERT INTO GENRES (name) VALUES ('Документальный');
INSERT INTO GENRES (name) VALUES ('Боевик');
